#!/usr/bin/env python3
# -*- coding: utf-8 -*-
'''
Calculate the number of genotypes per locus
'''

import argparse
import gzip

def count_geno():
	parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
	parser.add_argument("-i", "--input", action="store", dest="filename", required=True,help="Name of genotype(generated by iTools)")
	args = parser.parse_args()
	filename = args.filename
	
	pattern = {'-':'--','A':'AA','T':'TT','C':'CC','G':'GG','K':'GT','M':'AC','R':'AG','S':'CG','Y':'CT','W':'AT'}
	
	if filename.endswith('gz'):
		opener = gzip.open
	else:
		opener = open
	
	with opener(filename,'rt') as IN:
		for i in IN:
			geno= []
			if '#' in i:
				pass
			else:
				geno = [base for base in i.strip('\n').split(' ')]
			tmp = [pattern[x] if x in pattern else x for x in geno]
			set_geno = sorted(set(tmp))
			for e in set_geno:
				print(e,tmp.count(e),end=' ')
			print("\n",end='')

if __name__ == "__main__":
    count_geno()

